## Day 32 Lecture 1 Assignment

In this assignment, we will learn about K nearest neighbor regression. We will use the absenteeism at work dataset loaded below and analyze the model generated for this dataset.

In [0]:
%matplotlib inline

import math

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [0]:
absent = pd.read_csv('https://tf-assets-prod.s3.amazonaws.com/tf-curric/data-science/Absenteeism_at_work.csv', sep=';')

In [0]:
absent.head()

   ID  Reason for absence  ...  Body mass index  Absenteeism time in hours
0  11                  26  ...               30                          4
1  36                   0  ...               31                          0
2   3                  23  ...               31                          2
3   7                   7  ...               24                          4
4  11                  23  ...               30                          2

[5 rows x 21 columns]

Find which variables have the highest pairwise correlation and remove them from our dataset. Additionally, try to think of which variables are correlated by looking at the column names and remove those columns as well.

Note: When choosing between two categorical variables that are correlated, keep the one with fewer unique categories.

In [0]:
# answer below:

def get_redundant_pairs(df):
    '''Get diagonal and lower triangular pairs of correlation matrix'''
    pairs_to_drop = set()
    cols = df.columns
    for i in range(0, df.shape[1]):
        for j in range(0, i+1):
            pairs_to_drop.add((cols[i], cols[j]))
    return pairs_to_drop

def get_top_abs_correlations(df, n=5):
    au_corr = df.corr().abs().unstack()
    labels_to_drop = get_redundant_pairs(df)
    au_corr = au_corr.drop(labels=labels_to_drop).sort_values(ascending=False)
    return au_corr[0:n]

print("Top Absolute Correlations")
print(get_top_abs_correlations(absent.corr(), 40))

Top Absolute Correlations
Weight                           Body mass index                    0.950431
Service time                     Age                                0.883055
Reason for absence               Disciplinary failure               0.802325
Service time                     Body mass index                    0.782555
                                 Weight                             0.745689
ID                               Distance from Residence to Work    0.736515
Month of absence                 Hit target                         0.735402
ID                               Social drinker                     0.731977
Age                              Body mass index                    0.729449
Transportation expense           Pet                                0.703364
Education                        Social drinker                     0.700503
Age                              Weight                             0.699486
Service time                     Pet                                0.695162
Social drinker                   Body mass index                    0.623293
Education                        Body mass index                    0.622822
Distance from Residence to Work  Social drinker                     0.620905
Month of absence                 Seasons                            0.612917
Transportation expense           Son                                0.607909
Social drinker                   Weight                             0.606237
Age                              Pet                                0.594681
Service time                     Social drinker                     0.586050
Transportation expense           Service time                       0.563127
Distance from Residence to Work  Height                             0.548306
Education                        Weight                             0.547319
Transportation expense           Age                                0.535212
ID                               Body mass index                    0.503054
Service time                     Education                          0.476869
Age                              Education                          0.471472
Transportation expense           Distance from Residence to Work    0.447478
                                 Weight                             0.443945
Distance from Residence to Work  Education                          0.429360
ID                               Weight                             0.423949
                                 Service time                       0.420277
Pet                              Weight                             0.415775
Age                              Social drinker                     0.393801
Social smoker                    Weight                             0.391762
Transportation expense           Height                             0.382325
Social smoker                    Body mass index                    0.376917
Pet                              Body mass index                    0.345007
Transportation expense           Body mass index                    0.337422
dtype: float64

Find out which columns contain categorical variables and turn those into dummy variables.

In [0]:
# answer below:

categorical = absent.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

Split the data into train and test with test containing 20% of the data.

In [0]:
# answer below:

In [0]:
from sklearn.metrics import mean_squared_error

Train a KNN regression model using k=15 and compute the MSE for the training and test subsamples.

In [0]:
# answer below